### ISSUE TITLE
Input stream closes on Firefox.

### ISSUE THREAD

**Issue by brookemitchell** [cwilso/volume-meter#2]
Hi I'm trying to use this example and the input stream only lasts for 5 seconds on firefox (same with the input effects, but not audiorecorder?). Is this an issue with the examples or web audio api?

Thanks for taking a look at this, I'm more of an artist than a coder, the work with web audio is really exciting!

**Comment by cwilso** [comment]
I'm pretty sure, BTW, that this was because FF was garbage collecting the stream source even though it was connected to a node.  I edited the code in this repo, but haven't redeployed the fix to appspot yet.
