### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by laurent-le-graverend** [cwilso/volume-meter#3]
I saw what you wrote and thought the CPU issues would be caused by `createScriptProcessor`

Having between 30 to 45% CPU usage on this volume meter, I spend some time to look for ways to improve this.

In conclusion, it has nothing to do with it, this is cause by calling recursively `requestAnimationFrame`

This example with easily push your CPU usage to 30%:

```javascript
var canvas = document.createElement('canvas');
canvas.width = 100;
canvas.height = 20;
var canvasContext = canvas.getContext('2d');
document.body.appendChild(canvas)
var rafId;
function drawLoop(time) {
  canvasContext.clearRect(0, 0, 100, 20);
  canvasContext.fillRect(0, 0, Math.random() * 100 * 1.4, 20);
  rafID = window.requestAnimationFrame(drawLoop);
}
```

This repo is more about the web audio API usage, but do you have any suggestion to improve this?

**Comment by cwilso** [comment]
It definitely is keeping the CPU alive, because it's rendering; the composition could probably be improved (by smarter changes and not clearRect/fillRect every time) - but I don't see it driving that high in the profiler.  In fact, I don't ever see the composition taking more than 8ms or so.
