### ISSUE TITLE
Stream generation failed

### ISSUE THREAD

**Issue by rualark** [cwilso/volume-meter#5]
Hi! About a month ago this was working, but now shows "Stream generation failed" error in Chrome (I checked several PCs).

**Comment by cwilso** [comment]
Doh, that's because it needs to be forced to HTTPS now (or getUserMedia fails).  If you go to https://webaudiodemos.appspot.com/volume-meter/index.html, it works (or if you host locally).  Will update the site in the morning.

**Comment by cwilso** [comment]
Fixed deployment.

**Comment by rualark** [comment]
Thanks a lot for your answer!
Is there a way to enable this without HTTPS? I use Sourceforge Project Web and it does not support HTTPS at all.

**Comment by cwilso** [comment]
There is not.  (Other than using localhost, which is considered secure.)
