### ISSUE TITLE
http://webaudiodemos.appspot.com/volume-meter/ doesn't work

### ISSUE THREAD

**Issue by mozeq** [cwilso/volume-meter#6]
I get this error when trying to load the page in chromium:

```
getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
```

**Comment by martianyi** [comment]
I think we can use github pages to hold this demo since github pages support https.

**Comment by val-samonte** [comment]
either with github or with firebase hosting. firebase has https by default, and it can be easily deployed.

**Comment by martianyi** [comment]
Update: appspot.com support https, so you can just change to [https://webaudiodemos.appspot.com/volume-meter/ ](https://webaudiodemos.appspot.com/volume-meter/ ), it will work.

**Comment by cwilso** [comment]
fixed.
