### ISSUE TITLE
Stream generation failed even with HTTPS

### ISSUE THREAD

**Issue by rualark** [cwilso/volume-meter#9]
Hi!
For some reason I still get this error even with HTTPS protocol: Stream generation failed

I earlier created issue #5 for HTTP, but now HTTPS also seems to fail

**Comment by rualark** [comment]
I am sorry, I found out that now this error was due to no microphone in PC. Fixed

**Comment by bevinl** [comment]
I'm now having this problem on IOS safari only. it's https and   navigator.mediaDevices.getUserMedia, using AudioContext-MonkeyPatch to fit in,  but now the error moved to 'stream generation failed' (on ipad with microphone)
